{{- if and .Values.persistentVolume.enabled .Values.persistentVolume.customVolume .Values.persistentVolume.customVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "railsk8s.fullname" . }}-pv
  labels:
    {{- include "railsk8s.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/resource-policy: keep
  {{- with .Values.persistentVolume.customVolume.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .Values.persistentVolume.customVolume.specs | nindent 2 }}
{{- end }}