{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "railsk8s.fullname" . }}-seed
  labels:
    {{- include "railsk8s.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "railsk8s.fullname" . }}-seed
    spec:
      restartPolicy: Never
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args: ["-c", "bundle exec rake db:seed"]
        env:
          {{- toYaml .Values.env | nindent 10 }}
        {{- if .Values.envFrom }}
        envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
        {{- if .Values.persistentVolume.enabled }}
        volumeMounts:
          - name: {{ include "railsk8s.fullname" . }}-persistent-storage
            mountPath: {{ .Values.persistentVolume.mountPath }}
        {{- end }}    
      {{- if .Values.persistentVolume.enabled }}
      volumes:
      - name: {{ include "railsk8s.fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "railsk8s.fullname" . }}-pv-claim
      {{- end }}
{{- end }}